### PR TITLE
action-deps-version-bumps

### PR DESCRIPTION
**Pull request by 0815Creeper**

### CODE REVIEW

**Comment by ThummeTo** [comment]
PkgEval action fails, but runs under the latest release on main ... can you please check why?

**Comment by ThummeTo** [comment]
BTW: the same for FMIFlux, the error occurs after updating the versions inside of the action

**Comment by 0815Creeper** [comment]
on it

**Comment by 0815Creeper** [comment]
test/eval.jl specifys the use of julia 1.8 for FMIExport and 1.10 for FMI.jl and FMIFlux.jl. Is this intended?

**Comment by 0815Creeper** [comment]
I cannot easyly recreate the issue. As you can see here (https://github.com/ThummeTo/FMIFlux.jl/actions/runs/11126505172), it ran fine without any changes to the code before merging. Same when reproducing on the same code here (https://github.com/0815Creeper/FMIExport.jl/actions/runs/11400310616). Seems to be a sporadic event. I will try to find the cause anyway

**Pull request merged**
